// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PokemonGoRaidBot.Data;
using System;

namespace PokemonGoRaidBot.Migrations
{
    [DbContext(typeof(PokemonRaidBotDbContext))]
    partial class PokemonRaidBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("PokemonGoRaidBot.Data.Entities.DiscordChannelEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<DateTime>("FirstSeenDate");

                    b.Property<DateTime>("LastSeenDate");

                    b.Property<string>("Name");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("PokemonGoRaidBot.Data.Entities.DiscordServerEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<DateTime>("FirstSeenDate");

                    b.Property<DateTime>("LastSeenDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("PokemonGoRaidBot.Data.Entities.PokemonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokemonGoRaidBot.Data.Entities.RaidPostChannelEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ChannelId");

                    b.Property<ulong>("RaidPostId");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("RaidPostId");

                    b.ToTable("ChannelPosts");
                });

            modelBuilder.Entity("PokemonGoRaidBot.Data.Entities.RaidPostEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreationMessage");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("HasEndDate");

                    b.Property<int>("JoinCount");

                    b.Property<ulong>("LocationId");

                    b.Property<int>("PokemonId");

                    b.Property<DateTime>("PostedDate");

                    b.Property<int>("ResponseCount");

                    b.Property<ulong>("ServerId");

                    b.Property<string>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PokemonId");

                    b.HasIndex("ServerId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("PokemonGoRaidBot.Data.Entities.RaidPostLocationEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("Latitude");

                    b.Property<double?>("Longitude");

                    b.Property<string>("Name");

                    b.Property<ulong>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("PokemonGoRaidBot.Data.Entities.DiscordChannelEntity", b =>
                {
                    b.HasOne("PokemonGoRaidBot.Data.Entities.DiscordServerEntity", "Server")
                        .WithMany("Channels")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PokemonGoRaidBot.Data.Entities.RaidPostChannelEntity", b =>
                {
                    b.HasOne("PokemonGoRaidBot.Data.Entities.DiscordChannelEntity", "Channel")
                        .WithMany("PostChannels")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PokemonGoRaidBot.Data.Entities.RaidPostEntity", "Post")
                        .WithMany("ChannelPosts")
                        .HasForeignKey("RaidPostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PokemonGoRaidBot.Data.Entities.RaidPostEntity", b =>
                {
                    b.HasOne("PokemonGoRaidBot.Data.Entities.RaidPostLocationEntity", "Location")
                        .WithMany("Posts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PokemonGoRaidBot.Data.Entities.PokemonEntity", "Pokemon")
                        .WithMany("Posts")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PokemonGoRaidBot.Data.Entities.DiscordServerEntity", "Server")
                        .WithMany("Posts")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
